namespace Sadie.Networking.Events;

public static class EventHandlerId
{
    public const short ClientVersion = 4000;
    public const short ClientVariables = 1053;
    public const short InitDiffieHandshake = 3110;
    public const short CompleteDiffieHandshake = 773;
    public const short UniqueId = 2490;
    public const short SecureLogin = 2419;
    public const short PerformanceLog = 3230;
    public const short PlayerActivity = 3457;
    public const short PlayerData = 357;
    public const short PlayerBalance = 273;
    public const short PlayerSubscription = 3166;
    public const short NavigatorData = 2110;
    public const short PlayerFriendsList = 1523;
    public const short PlayerMessengerInit = 2781;
    public const short PlayerPong = 2596;
    public const short CompetitionTimingCode = 2912;
    public const short PlayerIgnoredUsers = 3878;
    public const short PlayerMeMenuSettings = 2388;
    public const short HotelViewBonusRare = 957;
    public const short GetBadgePointLimits = 1371;
    public const short GameCenterRequestGames = 741;
    public const short GetGameAchievementsMessage = 2399;
    public const short NavigatorPromotedRooms = 2908;
    public const short RoomCategories = 3027;
    public const short NavigatorEventCategories = 1782;
    public const short PlayerFriendRequestsList = 2448;
    public const short PlayerSanctionStatus = 2746;
    public const short GetTargetedOffer = 2487;
    public const short RoomLoaded = 2312;
    public const short GetInterstitial = 2519;
    public const short RoomHeightmap = 3898;
    public const short RoomHeightmap2 = 2300;
    public const short RoomUserChat = 1314;
    public const short RoomUserShout = 2085;
    public const short RoomUserWalk = 3320;
    public const short RoomUserDance = 2080;
    public const short RoomUserAction = 2456;
    public const short RoomUserStartTyping = 1597;
    public const short RoomUserStopTyping = 1474;
    public const short RoomUserWhisper = 1543;
    public const short RoomUserLookAt = 3301;
    public const short RoomUserSign = 1975;
    public const short RoomUserSit = 2235;
    public const short RoomUserTags = 17;
    public const short RoomForwardData = 2230;
    public const short RoomUserRespect = 2694;
    public const short SaveNavigatorSettings = 3159;
    public const short NavigatorSearch = 249;
    public const short PlayerChangedAppearance = 2730;
    public const short PlayerChangedMotto = 2228;
    public const short PlayerRelationships = 2138;
    public const short PlayerProfile = 3265;
    public const short PlayerWearingBadges = 2091;
    public const short PlayerFriendRequests = 3157;
    public const short PlayerAcceptFriendRequest = 137;
    public const short PlayerDeclineFriendRequest = 2890;
    public const short PlayerRemoveFriends = 1689;
    public const short PlayerChangeRelationship = 3768;
    public const short PlayerCreateRoom = 2752;
    public const short HabboClubData = 3285;
    public const short HabboClubCenter = 869;
    public const short HabboClubGifts = 487;
    public const short RoomUserGoToHotelView = 105;
    public const short PlayerSearch = 1210;
    public const short PlayerStalk = 3997;
    public const short PlayerSendDirectMessage = 3567;
    public const short RoomSettings = 3129;
    public const short RoomSettingsSave = 1969;
    public const short PlayerInventoryBadges = 2769;
    public const short RoomDoorbellAnswer = 1644;
    public const short PlayerAchievements = 219;
    public const short CameraPrice = 796;
    public const short CatalogMode = 1195;
    public const short CatalogMarketplaceConfig = 2597;
    public const short CatalogRecyclerLogic = 398;
    public const short CatalogGiftConfig = 418;
    public const short CatalogPurchaseGift = 1411; // buy a catalog item as a gift for another player
    public const short OpenPresent = 3558;         // open a placed present furni
    public const short RoomUserChangeChatBubble = 1030;
    public const short CatalogDiscount = 223;
    public const short CatalogIndex = 2529;
    public const short CatalogPage = 412;
    public const short CatalogPurchase = 3492;
    public const short PlayerFriendListUpdate = 1419;
    public const short HotelViewPromotions = 1827;
    public const short RoomLike = 3582;
    public const short PlayerInventoryFurnitureItems = 3150;
    public const short RoomItemPlaced = 1258;
    public const short RoomItemEjected = 3456;
    // Custom (non-Habbo) packet: admin permanent furniture deletion. Client sends
    // header 4001 with the furniture item id; see RoomItemDeleteEventHandler.
    public const short RoomItemDelete = 4001;
    // Custom (non-Habbo) Solana Club payment packets (client <-> emulator).
    public const short ClubPaymentIntent = 4002; // client asks for a payment intent (packageId)
    public const short ClubPaymentSubmit = 4003; // client submits the paid tx signature
    public const short ClubPaymentIntentResult = 4004; // server -> client: intent (treasury, amount, ref)
    public const short ClubPaymentResult = 4005;       // server -> client: grant outcome
    public const short RoomFloorFurnitureItemUpdated = 248;
    public const short RoomItemUse = 99;
    // Wall-item "use"/multistate toggle. The Nitro client sends a SEPARATE header
    // (FURNITURE_WALL_MULTISTATE = 210) for wall items vs floor items (99), so wall
    // items need their own handler — see RoomWallItemUseEventHandler.
    public const short RoomWallItemUse = 210;
    public const short RoomGiveUserRights = 808;
    public const short RoomRemoveUserRights = 2064;
    public const short PlayerWardrobe = 2742;
    public const short PlayerWardrobeSave = 800;
    public const short RoomWallItemUpdated = 168;
    public const short RoomPaintItemPlaced = 711;
    public const short PlayerSetHomeRoom = 1740;
    public const short GetCommunityGoalHallOfFame = 2167;
    public const short PlayerGroupBadges = 21;
    public const short GetPlayerGroupBadgeParts = 813;
    public const short PlayerInventoryBotItems = 3848;
    public const short RoomPlayerBotPlaced = 1592;
    public const short FloorPlanEditorDoorCoords = 3559;
    public const short FloorPlanEditorGetOccupiedTiles = 1687;
    public const short FloorPlanEditorSave = 875;
    public const short RoomDimmerSettings = 2813;
    public const short RoomDimmerToggle = 2296;
    public const short RoomDimmerSave = 1648;
    public const short RoomTriggerOneWayGate = 2765;
    public const short RoomTriggerDice = 1990;
    public const short RoomDelete = 532;
    public const short RoomBannedUsers = 2267;
    public const short RoomUserGiveHandItem = 2941;
    public const short RoomUserDropHandItem = 2814;
    public const short RoomCloseDice = 1533;
    public const short RoomUserTrade = 1481;
    public const short RoomUserTradeOfferItem = 3107;
    public const short RoomUserTradeClosed = 2551;
    public const short RoomUserTradeOfferItems = 1263;
    public const short RoomUserTradeAccepted = 3863;
    public const short RoomUserTradeConfirm = 2760;
    public const short RoomItemUpdateObjectData = 3608;
    public const short RoomBackgroundTonerApply = 2880;
    public const short ClientLatency = 295;
    public const short RoomWiredEffectSaved = 2281;
    public const short RoomWiredTriggerSaved = 1520;
    public const short RoomPollAnswer = 3505;
    public const short RoomPollReject = 1773;
    public const short RoomPollStart = 109;
    public const short RoomPollVoteCounter = 6200;
    public const short RedeemItem = 3115;
    public const short PlayerIgnoredUser = 1117;
    public const short PlayerRemoveUserIgnore = 2061;
    public const short ModToolsRoomAlert = 3842;
    public const short ModToolsUpdateRoomSettings = 3260;
    public const short ModToolsRoomInfo = 707;
    public const short ModToolsRoomChatLog = 2587;
}